# Generated by Django 2.0.5 on 2018-06-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhaar_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('otp', models.BigIntegerField()),
                ('txn_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain', models.TextField(blank=True, max_length=10000)),
                ('recording', models.FileField(blank=True, upload_to='')),
                ('aadhar_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efirapp.Aadhar')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efirapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Received'), (2, 'Registered'), (3, 'Investigating'), (4, 'Charge sheet filed')], default='Received', max_length=10)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('fir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efirapp.Complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='efirapp.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efirapp.State'),
        ),
    ]
