# Generated by Django 2.0.5 on 2018-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efirapp', '0002_auto_20180602_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Received', '1'), ('Registered', '2'), ('Investigating', '3'), ('Charge sheet filed', '4')], default='Received', max_length=10),
        ),
    ]
