# Generated by Django 2.0.5 on 2018-06-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efirapp', '0003_auto_20180602_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Registered'), ('3', 'Investigating'), ('4', 'Charge sheet filed')], default='Received', max_length=10),
        ),
    ]
